databases:
  - name: dollar-rates-db
    plan: free
    databaseName: dollar_rates

services:
  - type: web
    name: dollar-rates
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dollar-rates-db
          property: connectionString
